Name: IP
Type: FolderType
Children:
- Name: IP
  Type: BaseDataVariableType
  DataType: String
  Value: "0"
- Name: EOI_Nr
  Id: g=ce1c5d48520ce2e9087aff91718f077c
  Type: BaseDataVariableType
  DataType: Int32
  Value: 1
